version: '{build}'
image: Ubuntu1804
clone_depth: 2
configuration: Release

pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
  - git config --global core.autocrlf input
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_TAG" -ne "true") { $env:BUILD_VERSION="$env:APPVEYOR_BUILD_VERSION-pre" } Else { $env:BUILD_VERSION="$env:APPVEYOR_BUILD_VERSION" }
  - ps: 'Write-Output "GitHash: $env:GIT_HASH Build: $env:APPVEYOR_BUILD_VERSION Version: $env:BUILD_VERSION"'

#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - docker build --target testrunner -t foundatio:test --build-arg build=${BUILD_VERSION} .
  - mkdir artifacts
  - docker run -e APPVEYOR_API_URL --net=host -v $(pwd)/artifacts:/app/artifacts foundatio:test

after_test:
  - docker build --target publish -t foundatio:publish --build-arg build=${BUILD_VERSION} .
  - docker run --rm -it -v $(pwd)/artifacts:/app/artifacts foundatio:pack

artifacts:
  - path: artifacts\*.nupkg
    name: NuGet
  - path: test\Foundatio.Tests\bin\Release\netcoreapp2.0\BenchmarkDotNet.Artifacts\**\*
    name: Benchmarks

deploy:
  - provider: Environment
    name: MyGet
  - provider: Environment
    name: NuGet
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: GniMpFE62HprSyQNQoej/VSBnxn2GNnTrca3BnF8+ikMdqduO4Ts4t297teZF6wDAmGwnOtXusctUla8+WxLFkIztvVCS2Z1RG/DvEDYoc0=
    channel: '#notifications'
