version: 3.0.{build}
os: Visual Studio 2015
clone_depth: 2

environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  ES_VERSION: 1.7.3

install:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "3.0.0.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version} $(GIT_HASH)"

before_build:
  - nuget restore
  - ps: .\Build\Replace-FileString -Pattern '\$version\$' -Replacement "$env:appveyor_build_version" -Path src\**\*.nuspec -Overwrite

configuration: Release

build:
  project: Foundatio.sln
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

before_test:
  - cinst redis-64
  - redis-server --service-install
  - redis-server --service-start
  - ps: '& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start'
  - ps: .\Build\Start-ElasticSearch.ps1
  #- ps: .\Build\enable-rdp.ps1

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master

notifications:
  - provider: Slack
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
    channel: notifications
 