version: 3.0.{build}
os: Visual Studio 2015
clone_depth: 2

install:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - choco install gitlink

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "3.0.0.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version} $(GIT_HASH)"

before_build:
  - nuget restore
  - ps: .\Build\Replace-FileString -Pattern '\$version\$' -Replacement "$env:appveyor_build_version" -Path src\**\*.nuspec -Overwrite

configuration: Release

build:
  project: Foundatio.sln
  verbosity: minimal
  publish_nuget: true

before_package:
  - IF "%APPVEYOR_REPO_BRANCH%"=="master" GitLink .\

before_test:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - ps: '& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start'
  #- ps: .\Build\enable-rdp.ps1

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
 
